env: # Environt variable to pass to all tasks
    CIRRUS_CLONE_DEPTH: 1 # No need to clone with whole history
    CIRRUS_WORKING_DIR: "/tmp/ci" # Where to clone repo

task:
 name: builder # Project name
   timeout_in: 4h
     persistent_worker:
        labels:
           name: AX61-1
          isolation:
      container:
        image: accupara/aosp:latest
        cpu: 24
        memory: 120G
    install_reqs: # To sync source
      - git config --global user.name "Sanic" && git config --global user.email "kuromasan@yopmail.com" && git config --global credential.helper "cache --timeout=7200"
    download_ccache_background_script: # To download ccache in background
      - ./download_ccache # Ccache download script
    sync_script: # To sync source
      - ./sync # Source sync script
    monitor_background_script: # To monitor ccache and machine status every minute, runs in background
      - ./monitor # Monitor script
    build_script: # Actual build script foreground
      - ./build # Build script to run
    cont:
      - ./continue
