env: # Environment variable to pass to all tasks
  CIRRUS_CLONE_DEPTH: 1 # No need to clone with whole history
  CIRRUS_WORKING_DIR: "/tmp/ci" # Where to clone repo

task:
  name: builder # Project name
  timeout_in: 120m # Otherwise, it will timeout at 60m automatically; 120m is the highest in free account
  container:
    image: accupara/aosp:latest # It has built-in setup environment + repo, aria2, rclone, pigz, username ci, and email ci@ci.ci [You can use your own docker image if you want, or you can use this one too!]
    cpu: 8  # 8 CPU for dummy build, 10 or more CPUs for the final build; sometimes, more than 8 CPUs will cause a timelock, so you won't be able to run CI again within a few hours; in the build script, use -j8 or -j10 depending on what you used here, otherwise, a low memory issue will happen; 16 CPUs is the highest
    memory: 24G # So that we can have RAM when needed; 24G is the highest
  install_reqs: # To sync source
    - git config --global user.name "Sanic" && git config --global user.email "kuromasan@yopmail.com" && git config --global credential.helper "cache --timeout=7200"
  download_ccache_background_script: # To download ccache in the background
    - ./download_ccache # Ccache download script
  sync_script: # To sync source
    - ./sync # Source sync script
  monitor_background_script: # To monitor ccache and machine status every minute, runs in the background
    - ./monitor # Monitor script
  build_script: # Actual build script foreground
    - ./build # Build script to run
