#!/bin/bash
cd /tmp/rom # Depends on where source got synced

export ANDROID_JACK_VM_ARGS="-Dfile.encoding=UTF-8 -XX:+TieredCompilation -Xmx23G"
export LC_ALL=C

brunch aosp_nashc-userdebug -j8 